### ISSUE TITLE
Automated math lib tests

### ISSUE THREAD

**Issue by ghost** [jckarter/clay#153]
Generate tests for native math functions.

**Comment by jckarter** [comment]
@agemogolk Not sure how much more work this would be, but math modules seem to me like a good candidate for quickcheck-style fuzz testing, in addition to any concrete tests you write. The runtests.py script will run a test file name `test.clay` and determine its success or failure based on the exit code rather than on its stdout like it does with `main.clay` tests. A `test.clay` program for a math module could output the results of randomly-generated test cases and report the overall success or failure as the process exit code.

**Comment by ghost** [comment]
I'll give the complex stuff a once over and put up concrete trivial + special case tests. I'd already intended to knock-up some torture tests for the native math libs which should be trivial to drop into a test module. However, I probably won't have time to get on with that for a while - unfortunately I have some actual work to do.

**Comment by ghost** [comment]
I might get to this, might not. Too much work on now the holidays are over. Thesis to write and all that. Recommend making libm wrapper the default for math functions.

**Comment by jckarter** [comment]
A shame, but understandable. Is making libm the default relatively easy? How far along are your test cases? Which if any are complete enough just be enabled?

**Comment by ghost** [comment]
Libm can be made the default with minimum of fuss. Just a flag change and couple of other adjustments. All of the  non-complex argument routines i've uploaded are complete and tested over trivial and special cases. Although there might possibly be a small bug in the sin function.

There's a small test generator thing i was using in test/math/native/main-disabled.clay that could be trivially modified to generate a suitable 'out.txt'.

The other math mode routines (fast/approx/approx2) are completely untested, but were simply ported directly from C. Not really worth providing test cases for these as they are quick approximate hacks by design.

**Comment by jckarter** [comment]
Fixed by @agemogolk in #229
