### ISSUE TITLE
Allow variable bindings to declare types, bind pattern variables

### ISSUE THREAD

**Issue by jckarter** [jckarter/clay#246]
`var` etc. bindings should be able to declare types, e.g.:

```
var x:Int = 42;
```

It would also be convenient sometimes to be able to bind pattern variables from variable types, to extract otherwise difficult-to-derive type values:

```
var [E] elt:E = seq[0];
```

**Comment by ghost** [comment]
Joe, I've been tinkering with updates to the local bindings and managed to get them mostly working with the pattern matching system, which allows variadic assignment, pattern variables, typespecs, etc. The code is currently a little hackish and requires some filling out for error reporting and such. I've pushed it to my 'bindings' branch if you want a look (changes are mostly in codegenBindings, analyzeBindings, and the parser). Do you think this is a suitable solution or did you have something else in mind?

The current implementation breaks implicit unpacking, which can no doubt be fixed up. However I wonder if this should be kept in the language as it feels inconsistent with the use of ellipsis for all other multi-value unpack/variable statements.  This is particularly so when assigning to multi-value variables e.g. <code>var a, ..b = implict();</code>. I feel this should really be explicit and look similar to assigning a variadic variable like <code>var a, ..b = ..c; ..b = ..d; var a, ..b = ..explicit();</code> and so on.

What do think about making all multi-value unpacking explicit?

**Comment by jckarter** [comment]
Excellent. Re: implicit unpacking, It used to be that `..` was always required to be explicit, but that requirement was a common complaint from users. The unpack does feel redundant in cases like `var ..a = multiValues();`—the left-hand side of the binding makes it clear that multiple values are expected. If you could retain that behavior, that would be ideal. Currently it handles implicit unpacking by passing a `wantCount` greater than 1 to functions such as `codegenMulti` and `analyzeMulti`; a hacky but effective way to accomplish this for variadic bindings would be to just add 2 to the wantCount for a variadic binding.

**Comment by jckarter** [comment]
Is your math module pull request ready to be merged? There are a bunch of extraneous diffs in the master...bindings comparison diff.

**Comment by ghost** [comment]
Yeah, I think the math module stuff can be merged, however there may be 
an issue with non-linux test output. Probably just need to regenerate 
stuff. All tests pass for me. I've checked linux output and everything 
works as it should with regard to IEEE special cases. Just a few epsilon 
differences between native and libm output. The tests have been updated 
to use codepointers loops rather than deep nested static_for loops. This 
makes the math tests considerably faster.

I think I  branched the bindings from my working branch which already 
had the mathlib updates merged. The bindings are quite a way off being 
ready to merge, I need to tidy it up add ref/forward support.

I haven't included pattern predicate evaluation support in the local 
bindings system which would be fairly straight-forward, but probably not 
that useful. Hmm, unless you wanted to use it to check variadic variable 
types, what do you think?

Also, using this new local binding feature is going to introduce even 
more un-predicated pattern variable declarations (<code>[T] , [T,U], etc 
</code>). Had you considered using the implicit pattern variable 
shorthand that you introduced in new-clay <code>var a:'T = 2;</code>?  I 
guess this could be implemented in the parser . . .

**Comment by jckarter** [comment]
Predicate evaluation would be nice to have for consistency's sake, but I agree that it doesn't seem urgently useful. One possible use case I could see might be for verifying generic concepts, something like:

```
verifySequence(seq:S) {
    var [I | Iterator?(I)] iter = iterator(i);
}
```

Which would be useful with an SFINAE primitive that checked whether a particular generic instance can be instantiated.

Implicit pattern variables would be nice. A few people in #clay expressed their preference for explicitly declared pattern variables, but explicit declarations could be available as an option (similar to `forall` in Haskell type declarations).

**Comment by jckarter** [comment]
There's a syntax error in your mathlib branch:

```


[math/complex]
Failure: compiler error
Error:

 ###############################

 //
  * We always inline k_log1p(), since doing so produces a
 -^
  * substantial performance improvement (~40% on amd64).

 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/kernel/k_log.clay(12,1): error: parse error

[math/native]
Failure: compiler error
Error:

 ###############################

 //
  * We always inline k_log1p(), since doing so produces a
 -^
  * substantial performance improvement (~40% on amd64).

 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/kernel/k_log.clay(12,1): error: parse error

[math/sqrt]
Failure: compiler error
Error:

 ###############################

 //
  * We always inline k_log1p(), since doing so produces a
 -^
  * substantial performance improvement (~40% on amd64).

 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/kernel/k_log.clay(12,1): error: parse error

[operators/custom2]
Failure: compiler error
Error:

 ###############################

 //
  * We always inline k_log1p(), since doing so produces a
 -^
  * substantial performance improvement (~40% on amd64).

 ###############################
 /Users/joe/Documents/Code/others/clay/build/compiler/src/../../../lib-clay/math/native/kernel/k_log.clay(12,1): error: parse error
```

**Comment by ghost** [comment]
Fixed.

**Comment by jckarter** [comment]
Fixed by @agemogolk
